# Generated by Django 6.0.5 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
