# Generated by Django 6.0.5 on 2026-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=250)),
                ('workspace', models.CharField(blank=True, max_length=150, null=True)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='healthy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
