# Generated by Django 6.0.5 on 2026-07-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_message_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='is_safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='moderation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='scan_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
