# Generated by Django 6.0.5 on 2026-08-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupmessagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auto_add_members',
            field=models.BooleanField(default=False, help_text='If true, members may be auto-added to this group when created'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('MAIN', 'Main Workspace'), ('DEPARTMENT', 'Department Workspace'), ('CUSTOM', 'Custom Workspace')], default='CUSTOM', max_length=20),
        ),
    ]
