# Generated by Django 6.0.5 on 2026-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('hr', 'Human Resources'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
    ]
